modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "icon.png"
authors = "${mod_authors}"
description = '''
Nebula-Utils is a general-purpose utility mod maintained by the Nebula Team,
providing a collection of core functionalities, common systems, and extensible APIs,
designed to support the stable operation of the Nebula mod series and modpacks.
'''
[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = false
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = false
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "patchouli"
mandatory = false
versionRange = "[1.20.1-84.1-FORGE,)"

[[dependencies."${mod_id}"]]
modId = "kubejs"
mandatory = false
versionRange = "[2001.6.5-build.16,)"

[[dependencies."${mod_id}"]]
modId = "jei"
mandatory = false
versionRange = "[15,)"

[[dependencies."${mod_id}"]]
modId = "rhino"
mandatory = false
versionRange = "[2001.2.3-build.10,)"

[[dependencies."${mod_id}"]]
modId = "create"
mandatory = false
versionRange = "[0.5.1.j,6)"
ordering = "NONE"
side = "BOTH"